version: '3.8'

services:
  knights-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: